spring:
  profiles: local
  mvc:
    view:
      prefix: /WEB-INF/jsp/ 
      suffix: .jsp
  datasource:    
    #driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    #url: jdbc:log4jdbc:oracle:thin:@//172.17.2.26:1551/mallif
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@//172.17.2.26:1551/mallif
    username: RELAY
    password: 'Relay123$%^'   
  jpa:
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true   
  mail:
    host: localhost
    port: 2525
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: false       
---
server:
  port: 8083
  ssl:
    enabled: true
    key-store: $(context-path)/../config/keystore/local/keystore.p12 #  Key store 경로와 파일명
    key-store-type: PKCS12  # Key store 타입
    key-store-password: pulrelay  # Key store의 비밀번호
    key-alias: pulmuone # 키 스토어 별칭
---
tomcat:
  ajp:
    protocol: AJP/1.3
    port: 8084
---
dbclean:
  info:
    enabled: false
    backup: "6 month"
    period: "1 day"
    delete: "2 month"
    lock_wait: 3
    tables: [  
         { "table":"iflog", "column":"if_date", "format":"yyyymmddhh24miss", "type":"date" },
         { "table":"test_custord_info", "column":"sys_dat", "format":"yyyymmddhh24miss", "type":"date" },
         { "table":"test_custord_dtl", "column":"sys_dat", "format":"yyyymmddhh24miss", "type":"date" },
    ]
---    
logging:
  file: ./logs/log-file
  level:
    root: INFO
    com.pulmuone.OnlineIFServer.*: DEBUG
    org.hibernate:
      SQL: DEBUG
      type.descriptor.sql.BasicBinder: TRACE

