spring:
  profiles: dev
  mvc:
    view:
      prefix: /WEB-INF/jsp/ 
      suffix: .jsp
      
  datasource:    
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@//172.17.2.26:1551/mallif
    username: RELAY
    password: 'Relay123$%^'    
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      poolName: HikariCP
      connection-timeout: 120000
      validation-timeout: 120000
      ##timeout 시간 : 2분
      leak-detection-threshold: 300000
      ##커넥션 누수를 검사하여 pool에서 내보내는 시간 : 5분    
      
  jpa:
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    
  mail:
    host: 211.233.54.61
    port: 25
    username: 
    password: 
    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: false
          starttls:
            enable: true 
server:
  port: 8080
  ssl:
    enabled: true
    key-store: config/keystore/local/keystore.p12 # Key store 경로와 파일명 
    key-store-type: PKCS12  # Key store 타입
    key-store-password: pulrelay  # Key store의 비밀번호
    key-alias: pulmuone # 키 스토어 별칭
tomcat:
  ajp:
    protocol: AJP/1.3
    port: 8081
dbclean:
  info:
    enabled: true
    backup: "3 month"
    period: "1 day"
    delete: "2 month"
    lock_wait: 10
    tables: [
         { "table":"iflog", "column":"if_date", "format":"yyyymmddhh24miss", "type":"date" },
         { "table":"auth_log", "column":"auth_date", "format":"yyyymmddhh24miss", "type":"date" },
         { "table":"auth_meta", "column":"auth_date", "format":"yyyymmddhh24miss", "type":"date" },
         { "table":"tb_custord_info", "column":"sys_dat", "format":"yyyymmddhh24miss", "type":"date" },
         { "table":"tb_custord_dtl", "column":"sys_dat", "format":"yyyymmddhh24miss", "type":"date" },
         { "table":"tb_ordetc_info", "column":"sys_dat", "format":"yyyymmddhh24miss", "type":"date" },
         { "table":"tb_purchase_info", "column":"sys_dat", "format":"yyyymmddhh24miss", "type":"date" },
         { "table":"tb_purchase_dtl", "column":"sys_dat", "format":"yyyymmddhh24miss", "type":"date" },
         { "table":"ogh_inf_dsvhd_t", "column":"inf_date", "format":"yyyymmdd", "type":"text" },
         { "table":"ogh_inf_dsvdt_t", "column":"inf_date", "format":"yyyymmdd", "type":"text" },       
         { "table":"ogh_inf_order_t", "column":"inf_date", "format":"yyyymmdd", "type":"text" },
         { "table":"ogh_inf_ordmd_t", "column":"inf_date", "format":"yyyymmdd", "type":"text" },
         { "table":"ogh_inf_ordpo_t", "column":"inf_date", "format":"yyyymmdd", "type":"text" },
         { "table":"ogh_inf_ordrt_t", "column":"inf_date", "format":"yyyymmdd", "type":"text" },
         { "table":"ogh_scd_loanm_t", "column":"inf_date", "format":"yyyymmdd", "type":"text" },
         { "table":"ogh_spo_loan1_t", "column":"inf_date", "format":"yyyymmdd", "type":"text" },
         { "table":"ogh_spo_loan2_t", "column":"inf_date", "format":"yyyymmdd", "type":"text" },
         { "table":"ogh_inv_ledger_sub_sum_t", "column":"inf_date", "format":"yyyymmdd", "type":"text" },
         { "table":"ogh_xinvs_stock_silsa_t", "column":"inf_date", "format":"yyyymmdd", "type":"text" },
         { "table":"ogh_xinvs_store_trx_if_t", "column":"inf_date", "format":"yyyymmdd", "type":"text" },
         { "table":"ogh_invs_byorga_trx_if_t", "column":"inf_date", "format":"yyyymmdd", "type":"text" },
         { "table":"ogh_xwms_store_trx_if_t", "column":"inf_date", "format":"yyyymmdd", "type":"text" },
         { "table":"ogh_pos_rev_h_byorga_if_t", "column":"inf_date", "format":"yyyymmdd", "type":"text" },
         { "table":"ogh_pos_rev_d_byorga_if_t", "column":"inf_date", "format":"yyyymmdd", "type":"text" },
         { "table":"ogh_pos_rev_headers_if_t", "column":"inf_date", "format":"yyyymmdd", "type":"text" },
         { "table":"ogh_pos_rev_details_if_t", "column":"inf_date", "format":"yyyymmdd", "type":"text" },
         { "table":"ogh_pos_rev_ctrt_if_t", "column":"inf_date", "format":"yyyymmdd", "type":"text" },
         { "table":"ogh_xarf_cancle_trx_if_t", "column":"inf_date", "format":"yyyymmdd", "type":"text" },
         { "table":"ogh_lin_iface_no_t", "column":"inf_date", "format":"yyyymmdd", "type":"text" },
         { "table":"ogh_hdr_iface_no_t", "column":"inf_date", "format":"yyyymmdd", "type":"text" },
         { "table":"ogh_lin_iface_all_t", "column":"inf_date", "format":"yyyymmdd", "type":"text" },
         { "table":"ogh_hdr_iface_all_t", "column":"inf_date", "format":"yyyymmdd", "type":"text" },
         { "table":"ogh_pos_rev_card_if_t", "column":"inf_date", "format":"yyyymmdd", "type":"text" },
         { "table":"test_custord_info", "column":"sys_dat", "format":"yyyymmddhh24miss", "type":"date", "backup":"1 day"},
         { "table":"test_custord_dtl", "column":"sys_dat", "format":"yyyymmddhh24miss", "type":"date"},
         { "table":"tb_dlvzone_info", "column":"sys_dat", "format":"yyyymmdd", "type":"date", "backup":"0 day", "period":"1 day","flag":"Y"}
    ]
logging:
  file: ./logs/log-file
  level:
    com:
      zaxxer:
        hikari: DEBUG
    root: INFO
    com.pulmuone.OnlineIFServer.*: DEBUG
    org.hibernate:
      SQL: DEBUG
      type.descriptor.sql.BasicBinder: TRACE
